###

GET http://localhost:8080/products

###

GET http://localhost:8080/products/2

###

POST http://localhost:8080/products
content-type: application/json

{
  "id": 4,
  "name": "商品4",
  "price": 150
}

###

DELETE http://localhost:8080/products/2
content-type: application/json

###

PUT http://localhost:8080/products
content-type: application/json

{
  "id": 3,
  "name": "新商品3",
  "price": 800
}

###

PATCH http://localhost:8080/products/1
content-type: application/json

{
  "name": "新ネーム"
}

###